export const LoaderConfig = {
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/LineBetButton.png",
    GambleBg: "src/sprites/GambleBg.png",
    winPanel :  "/src/sprites/PanelWin.png",
    winPanel1:  "/src/sprites/PanelWin1.png",  
    bonusLogo: "src/sprites/BonusLogo.png",
    riskLogo: "src/sprites/RiskLogo.png",      
    balancePanel :  "/src/sprites/PanelBalance.png",
    doubleButton: "src/sprites/doubleButton.png",
    doubleButtonPressed : "src/sprites/doubleButtonPressed.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    linesNumber: "src/sprites/buttonBg.png",
    lineBox: "src/sprites/LineBox.png",
    paytableIcon :"src/sprites/PaytableIcon.png", 
    balanceBox: "src/sprites/BalanceBox.png",
    balanceText: "src/sprites/BalanceText.png",
    settingText: "src/sprites/SettingsText.png",
    rightPin: "src/sprites/rightPin.png",
    leftPin: "src/sprites/leftPin.png",
    on: "src/sprites/on.png",
    off: "src/sprites/off.png",
    onButton: "src/sprites/toggleOn.png",
    offButton: "src/sprites/toggleOff.png",
    toggleBar: "src/sprites/toggleBarBg.png",
    winLine: "src/sprites/winLine.png",
    yourWin: "src/sprites/YourWin.png",

    number0: "src/sprites/number1.png",
    number1: "src/sprites/number2.png",
    number2: "src/sprites/number3.png",
    number3: "src/sprites/number4.png",
    number4: "src/sprites/number5.png",
    number5: "src/sprites/number6.png",
    number6: "src/sprites/number7.png",
    number7: "src/sprites/number8.png",
    number8: "src/sprites/number9.png",
    number9: "src/sprites/number10.png",
    number10: "src/sprites/number11.png",
    number11: "src/sprites/number12.png",

    box0: "src/sprites/box0.png",
    box1: "src/sprites/box1.png",
    box2: "src/sprites/box2.png",
    box3: "src/sprites/box3.png",
    box4: "src/sprites/box4.png",
    box5: "src/sprites/box5.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",
    inofIcon9: "src/sprites/info9.png",
    inofIcon10: "src/sprites/info10.png",
    inofIcon11: "src/sprites/info11.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",
    PopupBackground: "src/sprites/popupBackground.png",
    messagePopup: "src/sprites/messagePopup.png",
    hugeWinPopup:"src/sprites/HugeWinPopup.png",
    megaWinPopup: "src/sprites/MegaWinPopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    infoCross: "src/sprites/infoCross.png",
    disconnectClose: "src/sprites/closeButton.png",
    BonusScenegame: "src/sprites/BonusSceneImage.jpg",
    riskGameimage: "src/sprites/RiskGameImage.jpg",
    dollar: 'src/sprites/dollarSign.png',
    payLines: "src/sprites/payLines.png",

    reelBg: "src/sprites/reelBackground.png",
    leftColumn: "src/sprites/left.png",
    rightColumn: "src/sprites/right.png",
    topColumn: "src/sprites/top.png",
    bottomColumn: "src/sprites/bottom.png",
    middleLine: "src/sprites/middleBars.png",
    gameLogo: "src/sprites/gameLogo.png",
    buttonBg: "src/sprites/buttonBg.png",
    totalBetText: "src/sprites/totalBetText.png",
    winText: "src/sprites/winText.png",
    megaWinText: "src/sprites/MegaWin.png",
    hugeWinText: "src/sprites/hugeWin.png",
    bigWinText: "src/sprites/BigWinText.png",
    jackpotText: "src/sprites/jackpotText.png",
    leftWinColumn: "src/sprites/woodenStick.png",
    rightWinColumn: "src/sprites/woodenStick.png",
    winPanelBalance: "src/sprites/biggerPanel.png",
    rightCoin: "src/sprites/rightCoin.png",
    leftCoin: "src/sprites/leftCoin.png",

    coin0: "src/sprites/coin1.png",
    coin1: "src/sprites/coin2.png",
    coin2: "src/sprites/coin3.png",
    coin3: "src/sprites/coin4.png",
    coin4: "src/sprites/coin5.png",
    coin5: "src/sprites/coin6.png",
    coin6: "src/sprites/coin7.png",
    coin7: "src/sprites/coin8.png",
    coin8: "src/sprites/coin9.png",
    coin9: "src/sprites/coin10.png",
    coin10: "src/sprites/coin11.png",
    coin11: "src/sprites/coin12.png",
    coin12: "src/sprites/coin13.png",
    coin13: "src/sprites/coin14.png",
    coin14: "src/sprites/coin15.png",
    coin15: "src/sprites/coin16.png",
    coin16: "src/sprites/coin17.png",
    coin17: "src/sprites/coin18.png",
    coin18: "src/sprites/coin19.png",
 
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    soundIndicator: "src/sprites/Indicator.png",
    indicatorSprite: "src/sprites/SliderButton.png",

    left0: "src/sprites/1.png",
    left1: "src/sprites/2.png",
    left2: "src/sprites/3.png",
    left3: "src/sprites/4.png",
    left4: "src/sprites/5.png",
    left5: "src/sprites/6.png",
    left6: "src/sprites/7.png",
    left7: "src/sprites/8.png",
    left8: "src/sprites/9.png",

    leftHover0: "src/sprites/LineNumber1.png",
    leftHover1: "src/sprites/LineNumber2.png",
    leftHover2: "src/sprites/LineNumber3.png",
    leftHover3: "src/sprites/LineNumber4.png",
    leftHover4: "src/sprites/LineNumber5.png",
    leftHover5: "src/sprites/LineNumber6.png",
    leftHover6: "src/sprites/LineNumber7.png",
    leftHover7: "src/sprites/LineNumber8.png",
    leftHover8: "src/sprites/LineNumber9.png",

    right0: "src/sprites/1.png",
    right1: "src/sprites/2.png",
    right2: "src/sprites/3.png",
    right3: "src/sprites/4.png",
    right4: "src/sprites/5.png",
    right5: "src/sprites/6.png",
    right6: "src/sprites/7.png",
    right7: "src/sprites/8.png",
    right8: "src/sprites/9.png",

    rightHover0: "src/sprites/LineNumber1.png",
    rightHover1: "src/sprites/LineNumber2.png",
    rightHover2: "src/sprites/LineNumber3.png",
    rightHover3: "src/sprites/LineNumber4.png",
    rightHover4: "src/sprites/LineNumber5.png",
    rightHover5: "src/sprites/LineNumber6.png",
    rightHover6: "src/sprites/LineNumber7.png",
    rightHover7: "src/sprites/LineNumber8.png",
    rightHover8: "src/sprites/LineNumber9.png",


    line0: "src/sprites/line1.png",
    line1: "src/sprites/line2.png",
    line2: "src/sprites/line3.png",
    line3: "src/sprites/line4.png",
    line4: "src/sprites/line5.png",
    line5: "src/sprites/line6.png",
    line6: "src/sprites/line7.png",
    line7: "src/sprites/line8.png",
    line8: "src/sprites/line9.png",

    blue0: "src/sprites/blue0.png",
    blue1: "src/sprites/blue1.png",
    blue2: "src/sprites/blue2.png",
    blue3: "src/sprites/blue3.png",
    blue4: "src/sprites/blue4.png",
    blue5: "src/sprites/blue5.png",
    blue6: "src/sprites/blue6.png",
    blue7: "src/sprites/blue7.png",
    blue8: "src/sprites/blue8.png",
    blue9: "src/sprites/blue9.png",
    blue10: "src/sprites/blue10.png",
    blue11: "src/sprites/blue11.png",
    blue12: "src/sprites/blue12.png",
    blue13: "src/sprites/blue13.png",
    blue14: "src/sprites/blue14.png",
    blue15: "src/sprites/blue15.png",
    blue16: "src/sprites/blue16.png",
    blue17: "src/sprites/blue17.png",
    blue18: "src/sprites/blue18.png",
    blue19: "src/sprites/blue19.png",
    blue20: "src/sprites/blue20.png",


    BackCard1: "src/sprites/Backcard1.png",
    BackCard2: "src/sprites/Backcard2.png",
    BackCard3: "src/sprites/Backcard3.png",
    collectButton: "src/sprites/CollectButton.png",

    SpadesA:"src/sprites/spadeA.png",
    Spades2: "src/sprites/spade2.png",
    Spades3: "src/sprites/spade3.png",
    Spades4: "src/sprites/spade4.png",
    Spades5: "src/sprites/spade5.png",
    Spades6: "src/sprites/spade6.png",
    Spades7: "src/sprites/spade7.png",
    Spades8: "src/sprites/spade8.png",
    Spades9: "src/sprites/spade9.png",
    Spades10: "src/sprites/spade10.png",
    SpadesJ: "src/sprites/spadeJ.png",
    SpadesQ: "src/sprites/spadeQ.png",
    SpadesK: "src/sprites/spadeK.png",

    HeartsA: "src/sprites/HeartA.png",
    Hearts2: "src/sprites/Heart2.png",
    Hearts3: "src/sprites/Heart3.png",
    Hearts4: "src/sprites/Heart4.png",
    Hearts5: "src/sprites/Heart5.png",
    Hearts6: "src/sprites/Heart6.png",
    Hearts7: "src/sprites/Heart7.png",
    Hearts8: "src/sprites/Heart8.png",
    Hearts9: "src/sprites/Heart9.png",
    Hearts10: "src/sprites/Heart10.png",
    HeartsJ: "src/sprites/HeartJ.png",
    HeartsQ: "src/sprites/HeartQ.png",
    HeartsK: "src/sprites/HeartK.png",

    ClubsA: "src/sprites/ClubA.png",
    Clubs2: "src/sprites/Club2.png",
    Clubs3: "src/sprites/Club3.png",
    Clubs4: "src/sprites/Club4.png",
    Clubs5: "src/sprites/Club5.png",
    Clubs6: "src/sprites/Club6.png",
    Clubs7: "src/sprites/Club7.png",
    Clubs8: "src/sprites/Club8.png",
    Clubs9: "src/sprites/Club9.png",
    Clubs10: "src/sprites/Club10.png",
    ClubsJ: "src/sprites/ClubJ.png",
    ClubsQ: "src/sprites/ClubQ.png",
    ClubsK: "src/sprites/ClubK.png",

    DiamondsA: "src/sprites/DiamondA.png",
    Diamonds2: "src/sprites/Diamond2.png",
    Diamonds3: "src/sprites/Diamond3.png",
    Diamonds4: "src/sprites/Diamond4.png",
    Diamonds5: "src/sprites/Diamond5.png",
    Diamonds6: "src/sprites/Diamond6.png",
    Diamonds7: "src/sprites/Diamond7.png",
    Diamonds8: "src/sprites/Diamond8.png",
    Diamonds9: "src/sprites/Diamond9.png",
    Diamonds10: "src/sprites/Diamond10.png",
    DiamondsJ: "src/sprites/DiamondJ.png",
    DiamondsQ: "src/sprites/DiamondQ.png",
    DiamondsK: "src/sprites/DiamondK.png",

    blueAnim51: "src/sprites/blueAnim51.png",
    blueAnim52: "src/sprites/blueAnim52.png",
    blueAnim53: "src/sprites/blueAnim53.png",
    blueAnim54: "src/sprites/blueAnim54.png",
    blueAnim55: "src/sprites/blueAnim55.png",
    blueAnim56: "src/sprites/blueAnim56.png",
    blueAnim57: "src/sprites/blueAnim57.png",
    blueAnim58: "src/sprites/blueAnim58.png",
    blueAnim59: "src/sprites/blueAnim59.png",
    blueAnim60: "src/sprites/blueAnim60.png",
    blueAnim61: "src/sprites/blueAnim61.png",
    blueAnim62: "src/sprites/blueAnim62.png",
    blueAnim63: "src/sprites/blueAnim63.png",
    blueAnim64: "src/sprites/blueAnim64.png",
    blueAnim65: "src/sprites/blueAnim65.png",
    blueAnim66: "src/sprites/blueAnim66.png",
    blueAnim67: "src/sprites/blueAnim67.png",

    green0: "src/sprites/green0.png",
    green1: "src/sprites/green1.png",
    green2: "src/sprites/green2.png",
    green3: "src/sprites/green3.png",
    green4: "src/sprites/green4.png",
    green5: "src/sprites/green5.png",
    green6: "src/sprites/green6.png",
    green7: "src/sprites/green7.png",
    green8: "src/sprites/green8.png",
    green9: "src/sprites/green9.png",
    green10: "src/sprites/green10.png",
    green11: "src/sprites/green11.png",
    green12: "src/sprites/green12.png",
    green13: "src/sprites/green13.png",
    green14: "src/sprites/green14.png",
    green15: "src/sprites/green15.png",
    green16: "src/sprites/green16.png",
    green17: "src/sprites/green17.png",
    green18: "src/sprites/green18.png",
    green19: "src/sprites/green19.png",
    green20: "src/sprites/green20.png",

    greenAnim51: "src/sprites/greenAnim51.png",
    greenAnim52: "src/sprites/greenAnim52.png",
    greenAnim53: "src/sprites/greenAnim53.png",
    greenAnim54: "src/sprites/greenAnim54.png",
    greenAnim55: "src/sprites/greenAnim55.png",
    greenAnim56: "src/sprites/greenAnim56.png",
    greenAnim57: "src/sprites/greenAnim57.png",
    greenAnim58: "src/sprites/greenAnim58.png",
    greenAnim59: "src/sprites/greenAnim59.png",
    greenAnim60: "src/sprites/greenAnim60.png",
    greenAnim61: "src/sprites/greenAnim61.png",
    greenAnim62: "src/sprites/greenAnim62.png",
    greenAnim63: "src/sprites/greenAnim63.png",
    greenAnim64: "src/sprites/greenAnim64.png",
    greenAnim65: "src/sprites/greenAnim65.png",
    greenAnim66: "src/sprites/greenAnim66.png",
    greenAnim67: "src/sprites/greenAnim67.png",

    purple0: "src/sprites/purple0.png",
    purple1: "src/sprites/purple1.png",
    purple2: "src/sprites/purple2.png",
    purple3: "src/sprites/purple3.png",
    purple4: "src/sprites/purple4.png",
    purple5: "src/sprites/purple5.png",
    purple6: "src/sprites/purple6.png",
    purple7: "src/sprites/purple7.png",
    purple8: "src/sprites/purple8.png",
    purple9: "src/sprites/purple9.png",
    purple10: "src/sprites/purple10.png",
    purple11: "src/sprites/purple11.png",
    purple12: "src/sprites/purple12.png",
    purple13: "src/sprites/purple13.png",
    purple14: "src/sprites/purple14.png",
    purple15: "src/sprites/purple15.png",
    purple16: "src/sprites/purple16.png",
    purple17: "src/sprites/purple17.png",
    purple18: "src/sprites/purple18.png",
    purple19: "src/sprites/purple19.png",
    purple20: "src/sprites/purple20.png",

    purpleAnim51: "src/sprites/purpleAnim51.png",
    purpleAnim52: "src/sprites/purpleAnim52.png",
    purpleAnim53: "src/sprites/purpleAnim53.png",
    purpleAnim54: "src/sprites/purpleAnim54.png",
    purpleAnim55: "src/sprites/purpleAnim55.png",
    purpleAnim56: "src/sprites/purpleAnim56.png",
    purpleAnim57: "src/sprites/purpleAnim57.png",
    purpleAnim58: "src/sprites/purpleAnim58.png",
    purpleAnim59: "src/sprites/purpleAnim59.png",
    purpleAnim60: "src/sprites/purpleAnim60.png",
    purpleAnim61: "src/sprites/purpleAnim61.png",
    purpleAnim62: "src/sprites/purpleAnim62.png",
    purpleAnim63: "src/sprites/purpleAnim63.png",
    purpleAnim64: "src/sprites/purpleAnim64.png",
    purpleAnim65: "src/sprites/purpleAnim65.png",
    purpleAnim66: "src/sprites/purpleAnim66.png",
    purpleAnim67: "src/sprites/purpleAnim67.png",

    red0: "src/sprites/red0.png",
    red1: "src/sprites/red1.png",
    red2: "src/sprites/red2.png",
    red3: "src/sprites/red3.png",
    red4: "src/sprites/red4.png",
    red5: "src/sprites/red5.png",
    red6: "src/sprites/red6.png",
    red7: "src/sprites/red7.png",
    red8: "src/sprites/red8.png",
    red9: "src/sprites/red9.png",
    red10: "src/sprites/red10.png",
    red11: "src/sprites/red11.png",
    red12: "src/sprites/red12.png",
    red13: "src/sprites/red13.png",
    red14: "src/sprites/red14.png",
    red15: "src/sprites/red15.png",
    red16: "src/sprites/red16.png",
    red17: "src/sprites/red17.png",
    red18: "src/sprites/red18.png",
    red19: "src/sprites/red19.png",
    red20: "src/sprites/red20.png",

    //red gem break anim
    redAnim51: "src/sprites/redAnim51.png",
    redAnim52: "src/sprites/redAnim52.png",
    redAnim53: "src/sprites/redAnim53.png",
    redAnim54: "src/sprites/redAnim54.png",
    redAnim55: "src/sprites/redAnim55.png",
    redAnim56: "src/sprites/redAnim56.png",
    redAnim57: "src/sprites/redAnim57.png",
    redAnim58: "src/sprites/redAnim58.png",
    redAnim59: "src/sprites/redAnim59.png",
    redAnim60: "src/sprites/redAnim60.png",
    redAnim61: "src/sprites/redAnim61.png",
    redAnim62: "src/sprites/redAnim62.png",
    redAnim63: "src/sprites/redAnim63.png",
    redAnim64: "src/sprites/redAnim64.png",
    redAnim65: "src/sprites/redAnim65.png",
    redAnim66: "src/sprites/redAnim66.png",
    redAnim67: "src/sprites/redAnim67.png",

    yellow0: "src/sprites/yellow0.png",
    yellow1: "src/sprites/yellow1.png",
    yellow2: "src/sprites/yellow2.png",
    yellow3: "src/sprites/yellow3.png",
    yellow4: "src/sprites/yellow4.png",
    yellow5: "src/sprites/yellow5.png",
    yellow6: "src/sprites/yellow6.png",
    yellow7: "src/sprites/yellow7.png",
    yellow8: "src/sprites/yellow8.png",
    yellow9: "src/sprites/yellow9.png",
    yellow10: "src/sprites/yellow10.png",
    yellow11: "src/sprites/yellow11.png",
    yellow12: "src/sprites/yellow12.png",
    yellow13: "src/sprites/yellow13.png",
    yellow14: "src/sprites/yellow14.png",
    yellow15: "src/sprites/yellow15.png",
    yellow16: "src/sprites/yellow16.png",
    yellow17: "src/sprites/yellow17.png",
    yellow18: "src/sprites/yellow18.png",
    yellow19: "src/sprites/yellow19.png",
    yellow20: "src/sprites/yellow20.png",

    yellowAnim51: "src/sprites/yellowAnim51.png",
    yellowAnim52: "src/sprites/yellowAnim52.png",
    yellowAnim53: "src/sprites/yellowAnim53.png",
    yellowAnim54: "src/sprites/yellowAnim54.png",
    yellowAnim55: "src/sprites/yellowAnim55.png",
    yellowAnim56: "src/sprites/yellowAnim56.png",
    yellowAnim57: "src/sprites/yellowAnim57.png",
    yellowAnim58: "src/sprites/yellowAnim58.png",
    yellowAnim59: "src/sprites/yellowAnim59.png",
    yellowAnim60: "src/sprites/yellowAnim60.png",
    yellowAnim61: "src/sprites/yellowAnim61.png",
    yellowAnim62: "src/sprites/yellowAnim62.png",
    yellowAnim63: "src/sprites/yellowAnim63.png",
    yellowAnim64: "src/sprites/yellowAnim64.png",
    yellowAnim65: "src/sprites/yellowAnim65.png",
    yellowAnim66: "src/sprites/yellowAnim66.png",
    yellowAnim67: "src/sprites/yellowAnim67.png",


    slots0_0 :  "/src/sprites/Symbols/icon1/icon1.png",
    slots1_0 :  "/src/sprites/Symbols/icon2/icon1.png",
    slots2_0 :  "/src/sprites/Symbols/icon3/Icon_3.png",
    slots3_0 :  "/src/sprites/Symbols/icon4/icon_4.png",
    slots4_0 :  "/src/sprites/Symbols/icon5/icon_5.png",
    slots5_0 :  "/src/sprites/Symbols/icon6/icon_6.png",
    slots6_0 :  "/src/sprites/Symbols/icon7/icon_7.png",
    slots7_0 :  "/src/sprites/Symbols/icon8/icon_8.png",
    slots8_0 :  "/src/sprites/Symbols/icon9/Bonus.png",
    slots9_0 :  "/src/sprites/Symbols/icon10/Wild.png",
    slots10_0 :  "/src/sprites/Symbols/icon11/Jackpot.png",

    megawinAnimBg: "src/sprites/rays.png",
    megawinStar: "src/sprites/stars.png",

    man0: "src/sprites/man0.png",
    man1: "src/sprites/man1.png",
    man2: "src/sprites/man2.png",
    man3: "src/sprites/man3.png",
    man4: "src/sprites/man4.png",
    man5: "src/sprites/man5.png",
    man6: "src/sprites/man6.png",
    man7: "src/sprites/man7.png",
    man8: "src/sprites/man8.png",
    man9: "src/sprites/man9.png",
    man10: "src/sprites/man10.png",
    man11: "src/sprites/man11.png",
    man12: "src/sprites/man12.png",
    man13: "src/sprites/man13.png",
    man14: "src/sprites/man14.png",
    man15: "src/sprites/man15.png",
    man16: "src/sprites/man16.png",
    man17: "src/sprites/man17.png",
    man18: "src/sprites/man18.png",
    man19: "src/sprites/man19.png",
    man20: "src/sprites/man20.png",
    man21: "src/sprites/man21.png",
    man22: "src/sprites/man22.png",
    man23: "src/sprites/man23.png",
    man24: "src/sprites/man24.png",
    man25: "src/sprites/man25.png",
    man26: "src/sprites/man26.png",
    man27: "src/sprites/man27.png",
    man28: "src/sprites/man28.png",
    man29: "src/sprites/man29.png",
    man30: "src/sprites/man30.png",
    man31: "src/sprites/man31.png",
    man32: "src/sprites/man32.png",
    man33: "src/sprites/man33.png",

    winning0: "src/sprites/winning87.png",
    winning1: "src/sprites/winning88.png",
    winning2: "src/sprites/winning89.png",
    winning3: "src/sprites/winning90.png",
    winning4: "src/sprites/winning91.png",
    winning5: "src/sprites/winning92.png",
    winning6: "src/sprites/winning93.png",
    winning7: "src/sprites/winning94.png",
    winning8: "src/sprites/winning95.png",
    winning9: "src/sprites/winning96.png",
    winning10: "src/sprites/winning97.png",
    winning11: "src/sprites/winning98.png",
    winning12: "src/sprites/winning99.png",
    winning13: "src/sprites/winning100.png",
    winning14: "src/sprites/winning101.png",
    winning15: "src/sprites/winning102.png",
    winning16: "src/sprites/winning103.png",
    winning17: "src/sprites/winning104.png",
    winning18: "src/sprites/winning105.png",
    winning19: "src/sprites/winning106.png",
    winning20: "src/sprites/winning107.png",
    winning21: "src/sprites/winning108.png",
    winning22: "src/sprites/winning109.png",
    winning23: "src/sprites/winning110.png",
    winning24: "src/sprites/winning111.png",
    winning25: "src/sprites/winning112.png",
    winning26: "src/sprites/winning113.png",
    winning27: "src/sprites/winning114.png",
    winning28: "src/sprites/winning115.png",
    winning29: "src/sprites/winning116.png",
    winning30: "src/sprites/winning117.png",
    winning31: "src/sprites/winning118.png",
    winning32: "src/sprites/winning119.png",
    winning33: "src/sprites/winning120.png",
    winning34: "src/sprites/winning121.png",
    winning35: "src/sprites/winning122.png",
    winning36: "src/sprites/winning123.png",
    winning37: "src/sprites/winning124.png",
    winning38: "src/sprites/winning125.png",
    winning39: "src/sprites/winning126.png",
    winning40: "src/sprites/winning127.png",
    winning41: "src/sprites/winning128.png",
    winning42: "src/sprites/winning129.png",
    winning43: "src/sprites/winning130.png",
    winning44: "src/sprites/winning131.png",
    winning45: "src/sprites/winning132.png",
    winning46: "src/sprites/winning133.png",
    winning47: "src/sprites/winning134.png",
    winning48: "src/sprites/winning135.png",
    winning49: "src/sprites/winning136.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    GhostKid : "src/fonts/GhostKidAOE_Pro.otf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/Teaser.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/spin.wav",
        winMusic: "src/sounds/JackpotWinner.wav",
        buttonpressed: "src/sounds/Game-Button.wav",
        bonusBg: "src/sounds/bonusbg.mp3",
        bonuswin: "src/sounds/bonuswin.mp3",
 
};
